base_url = "https://prashantrahul.com"
title = "/prashant"
description = "I am a software developer working in a lot of fields with a specialization in building and tinkering compilers and interpreters. I also work on creating full-stack web experiences, emulators, graphics APIs, games and cross platform applications."
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/prashantrahul141/prashantrahul141.github.io"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
]

socials = [
    { name = "twitter", url = "https://x.com/prashrahul141/", icon = "twitter" },
    { name = "github", url = "https://github.com/prashantrahul141/", icon = "github" },
]

stylesheets = [
    #"custom.css"    # at /static/custom.css
]

[extra.analytics]
enabled = false
