[data.user.pinnedItems]
totalCount = 6

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "zspie"
description = " A fast, easy, dynamic programming language for beginners."
url = "https://github.com/prashantrahul141/zspie"
stargazerCount = 2

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLMMm1c4D9seY"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNj"
name = "c"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLMMm1c4D9seZ"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNjb21waWxlcg=="
name = "compiler"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLMMm1c4D9sea"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNwcm9ncmFtbWluZy1sYW5ndWFnZQ=="
name = "programming-language"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UxNDk="
name = "C"
color = "#555555"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "splax"
description = "A memory safe, easy, dynamic programming language."
url = "https://github.com/prashantrahul141/splax"
stargazerCount = 0

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLF4gas4D1mCj"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNpbnRlcnByZXRlcg=="
name = "interpreter"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLF4gas4D1mCk"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNsZXhlcg=="
name = "lexer"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOLF4gas4D1mCl"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNwYXJzZXI="
name = "parser"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UyNDk="
name = "Rust"
color = "#dea584"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "cipi8"
description = "Chip8 emulator implementation in c++"
url = "https://github.com/prashantrahul141/cipi8"
stargazerCount = 0

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOM1QXYM4EhnoS"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNjaGlwOA=="
name = "chip8"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOM1QXYM4EhnoT"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNjaGlwOC1lbXVsYXRvcg=="
name = "chip8-emulator"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOM1QXYM4EhnoU"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNjcHA="
name = "cpp"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UxNDI="
name = "C++"
color = "#f34b7d"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "taurl"
description = "Fast url shortner written entirely in go."
url = "https://github.com/prashantrahul141/taurl"
stargazerCount = 0

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOMCuAz84EOOL9"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNnaW4="
name = "gin"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOMCuAz84EOOL-"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNnb2xhbmc="
name = "golang"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOMCuAz84EOOL_"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWN1cmwtc2hvcnRlbmVy"
name = "url-shortener"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UxOTA="
name = "Go"
color = "#00ADD8"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "plex"
description = "A Social Media Web App."
url = "https://github.com/prashantrahul141/plex"
stargazerCount = 8

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOI4WolM4C7kIX"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "TO_kgCtY3JlYXRlLXQzLWFwcA"
name = "create-t3-app"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOI4WolM4C7kIY"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNuZXh0LWF1dGg="
name = "next-auth"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOI4WolM4C7kIZ"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNuZXh0anM="
name = "nextjs"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UyODc="
name = "TypeScript"
color = "#3178c6"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"

[[data.user.pinnedItems.edges]]
[data.user.pinnedItems.edges.node]
name = "BlogWebApiDotNet"
description = "Web Apis for a simple blogging app using ASP .NET 8"
url = "https://github.com/prashantrahul141/BlogWebApiDotNet"
stargazerCount = 0

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOL4oQic4EMFGn"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNhc3AtbmV0"
name = "asp-net"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOL4oQic4EMFGo"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNjc2hhcnA="
name = "csharp"

[[data.user.pinnedItems.edges.node.repositoryTopics.edges]]
[data.user.pinnedItems.edges.node.repositoryTopics.edges.node]
id = "RT_kwDOL4oQic4EMFGp"

[data.user.pinnedItems.edges.node.repositoryTopics.edges.node.topic]
id = "MDU6VG9waWNkb3RuZXQ="
name = "dotnet"

[data.user.pinnedItems.edges.node.primaryLanguage]
id = "MDg6TGFuZ3VhZ2UyMzI="
name = "C#"
color = "#178600"

[data.user.pinnedItems.edges.node.owner]
login = "prashantrahul141"
